### ISSUE TITLE
Unable to use Markee in REACT

### ISSUE THREAD

**Issue by ReactUser2** [ashubham/markee#1]
In REACT :
import { Markee } from 'markee';
console.log(Markee, 'here is the Markee');

undefined "here is the Markee"  <<<<<  Markee is undefined after import

---------------------------------
Using the code sample from codepen within React fails :

TypeError: Cannot read property 'default' of undefined
    at ProxyComponent.componentDidMount

**Comment by ashubham** [comment]
@ReactUser2 Seems your module loader is not able to identify this correctly.

Have you tried
```javascript
import Markee from 'markee';

console.log(Markee); // Should have Markee Class Constructor.
```

**Comment by ReactUser2** [comment]
Hi Ashish,
Thanks for your quick response. Yes. The first thing I tried before was to check the value of the Markee object returned from the import. I have tried both
import { Markee } from 'markee'
and
import Markee from 'markee'
and they both return 'undefined'

**Comment by ashubham** [comment]
@ReactUser2 Sorry for being super late, and maybe this is not relevant to you anymore.

Did you also try `import * as Markee from 'markee` ?
